### ISSUE TITLE
TODO 2.1.x

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react#43]
- [x] write doc
- [x] https://github.com/ProjectSeptemberInc/gl-react-dom/commit/caef65ad11e1ecc5e5490b2c705a1d5e234e75d2#commitcomment-15227730
- [x] make it work with directly depending on React for incoming React Native dep
  - [x] remove all reference to previous hack of injecting React in documentation
  - [x] update all examples to fix all warnings
  - [ ] release new version of gl-react libs
- [x] update versions and deps
- [x] write release notes
- [x] test all RN example on ios and android
